apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector.tracing.svc.cluster.local:4318"
  SPRING_PROFILES_ACTIVE: "kubernetes"
