apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices
resources:
  - ../../../base/user-service
images:
  - name: ghcr.io/your-org/user-service
    newName: user-service
    newTag: "latest"
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
