apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  labels:
    app: krakend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:2.6.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend/krakend.json
              subPath: krakend.json
          livenessProbe:
            httpGet:
              path: /__health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
