apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices
resources:
  - ../../../base/user-service
images:
  - name: ghcr.io/thaothe37na/user-service
    newTag: "latest"
